<a href="https://colab.research.google.com/github/CristovamOliver/Machine-Learning/blob/develop/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Preço Compra/Aluguel de casas em São Paulo - Capital**

**Nome do dataset:** housing_sp_city.

**Objetivo:**
1 - Análise exploratória dos dados.
2 - Machine Learning (ML) para prever custos das moradias na metrópole de SP.

**Objetivo pessoal:**
Treinar capacidade de analisar dados;
Aplicar diferentes algorítmos de ML para visualizar na prática o seu funcionamento.

# Importando Bibliotecas

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns

# Importando Dataset

In [20]:
base = "https://raw.githubusercontent.com/CristovamOliver/Machine-Learning/develop/DataSet/housing_sp_city.csv"
dados = pd.read_csv(base,  encoding = "latin-1")

In [21]:
dados.head()

           logradouro numero  ... preco_aluguel  iptu_ano
0  Rua Juvenal Galeno     53  ...           NaN       NaN
1         Rua Juruaba     16  ...           NaN       NaN
2    Avenida Paulista    402  ...       29829.0    4040.0
3        Rua Alvorada   1190  ...           NaN    1610.0
4        Rua Curitiba    380  ...           NaN   18900.0

[5 rows x 18 columns]

In [22]:
dados.describe()

                cep     area_util  ...  preco_aluguel      iptu_ano
count  1.280560e+05  1.308680e+05  ...   2.871400e+04  1.146120e+05
mean   3.550899e+06  2.244307e+02  ...   1.102183e+04  4.182520e+03
std    2.177019e+06  5.764345e+03  ...   7.701223e+04  8.501091e+05
min    0.000000e+00  1.000000e+00  ...   0.000000e+00  0.000000e+00
25%    2.312135e+06  6.200000e+01  ...   2.310000e+03  0.000000e+00
50%    3.413030e+06  1.080000e+02  ...   4.111500e+03  8.400000e+01
75%    4.576050e+06  2.000000e+02  ...   9.100000e+03  3.640000e+02
max    9.981030e+07  2.025000e+06  ...   1.190000e+07  2.830242e+08

[8 rows x 10 columns]

In [23]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133964 entries, 0 to 133963
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   logradouro       126962 non-null  object
 1   numero           89823 non-null   object
 2   bairro           133943 non-null  object
 3   cep              128056 non-null  float64
 4   cidade           133964 non-null  object
 5   tipo_imovel      133964 non-null  object
 6   area_util        130868 non-null  float64
 7   banheiros        133051 non-null  float64
 8   suites           120347 non-null  float64
 9   quartos          130945 non-null  float64
 10  vagas_garagem    129539 non-null  float64
 11  anuncio_criado   133964 non-null  object
 12  tipo_anuncio     133964 non-null  object
 13  preco_venda      133964 non-null  int64
 14  taxa_condominio  117127 non-null  float64
 15  periodicidade    29051 non-null   object
 16  preco_aluguel    28714 non-null   float64
 17  iptu_ano         114612 non-null  float64
dtypes: float64(9), int64(1), object(8)
memory usage: 18.4+ MB

In [24]:
dados.isnull().count()

logradouro         133964
numero             133964
bairro             133964
cep                133964
cidade             133964
tipo_imovel        133964
area_util          133964
banheiros          133964
suites             133964
quartos            133964
vagas_garagem      133964
anuncio_criado     133964
tipo_anuncio       133964
preco_venda        133964
taxa_condominio    133964
periodicidade      133964
preco_aluguel      133964
iptu_ano           133964
dtype: int64

In [25]:
dados.shape

(133964, 18)